# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

methCall <- function(read1, type, nolap = FALSE, minqual = 20L, mincov = 10L, phred64 = FALSE, CpGfile = "", CHHfile = "", CHGfile = "") {
    invisible(.Call('methylKit_methCall', PACKAGE = 'methylKit', read1, type, nolap, minqual, mincov, phred64, CpGfile, CHHfile, CHGfile))
}

readBam <- function(bampath) {
    .Call('methylKit_readBam', PACKAGE = 'methylKit', bampath)
}

methCall_ <- function(read1, type, nolap = FALSE, minqual = 20L, mincov = 10L, phred64 = FALSE, CpGfile = "", CHHfile = "", CHGfile = "") {
    .Call('methylKit_methCall_', PACKAGE = 'methylKit', read1, type, nolap, minqual, mincov, phred64, CpGfile, CHHfile, CHGfile)
}

